//请求的api路径列表
export default {
  'GET_USER_URL': 'user/getUserInfo',
  'GET_USER_BY_ID_URL': 'user/getUserInfoById',
  'LOGIN_URL': 'user/login',
  'REGISTER_URL': 'user/register',
  'MY_MESSAGE_URL': 'message/getSelfMessageList',
  'UPDATE_MESSAGE_URL': 'message/updateMessage',
  'REPLY_INFO_URL': 'reply/getCurrentUserReplyinfo',
  'GET_REPLYINFO_BY_USER_URL': 'reply/getUserReplyinfo',
  'GET_REPLYINFOVO_BY_USER_URL': 'reply/getUserReplyinfoVo',
  'GET_REPLYINFOVO_BY_REPLYINFO_URL': 'reply/getUserReplyinfoVoByReply',
  'GET_USER_CLASS_URL': 'user/getCurrentUserClass',
  'GET_USER_REPLYGROUP_URL': 'replygroup/getCurrentUserReplygroup',
  'GET_QUESTIONS_URL': 'question/getQuestionsByReply',
  'SEND_MESSAGE_URL': 'message/sendMessage',
  'REPLY_QUESTION_URL': 'question/replyQuestion',
  'AUDIO_TO_TEXT_URL': 'question/audioToText',
  'SUBMIT_FEEDBACK_URL': 'feedback/submitFeedback',
  'UPDATE_CURRENT_USER_URL': 'user/updateCurrentUser',
  'GET_REPLYGROUPVO_BY_USER_URL': 'replygroup/getReplygroupVoByUser',
  'SUBMIT_SPEECH_URL': 'reply/submitSpeech',
  'ADD_QUESTION_URL': 'question/addQuestion',
  'ADD_SCORE_URL': 'score/addScore',
  'GET_SCORE_BY_REPLYINFO_SCORE_URL': 'score/queryScoreByReply',
  'UPDATE_REPLYINFO_URL': 'reply/updateReplyinfo',
}
